---
- hosts: nvite-rsvp-app
  vars:
    username: kevin
    hostname: nvite-rsvp-app
  tasks:
  - name: update the system
    pacman:
      upgrade: yes
  - name: Add user group
    group:
      name: "{{ username }}"
      state: present
  - name: Add user
    user:
      name: "{{ username }}"
      group: "{{ username }}"
      comment: developer
      shell: /bin/bash
      password: $1$EQqmRycr$l4EudPquzvidaRNSqlw810 #openssl passwd -1
      state: present
  - name: install node version manager (nvm)
    shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    args:
      creates: "/home/{{username}}/.nvm/nvm.sh"
    become: yes
    become_user: "{{username}}"
    become_method: su
  - name: Install packages
    pacman:
      name:
      - git
      - net-tools
      - vim
      - make
      - gcc
      state: present
  - name: change the hostname
    command: hostnamectl set-hostname "{{ hostname }}"



