---
- hosts: tinacms-dev
  tasks:
  - name: update the system
    pacman:
      upgrade: yes
  - name: Add tinacms Group
    group:
      name: tinacms
      state: present
  - name: Add tinacms user
    user:
      name: tinacms
      group: tinacms
      comment: tinacms developer
      shell: /bin/bash
      password: $1$RbR6Ej.4$L/Rp3S1vheMbcPI8Y5Hob. #openssl passwd -1
      state: present
  - name: install node version manager (nvm)
    shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
    args:
      creates: /home/tinacms/.nvm/nvm.sh
    become: yes
    become_user: tinacms
    become_method: su
  - name: Install git and net tools and vim
    pacman:
      name:
      - git
      - net-tools
      - vim
      state: present



